api_tokens:
  - name: pulumi
    userid: root@pam
    bws_project_id: 2811ce4d-da08-4937-88dd-b25800f4afe2
    bws_token_name_prefix: PROXMOX_API_TOKEN
  - name: pve-dev-backup
    userid: pve-dev@pbs
    bws_project_id: 2811ce4d-da08-4937-88dd-b25800f4afe2
    bws_token_name_prefix: PROXMOX_API_TOKEN
