- name: Query existing tokens
  ansible.builtin.command: pveum user token list {{ api_token.userid }} --output-format=json
  register: query_tokens_result
  changed_when: false
  check_mode: false

- name: Create and store API token
  when:
    query_tokens_result.stdout
      | from_json
      | selectattr('tokenid', 'equalto', api_token.name)
      | list
      | length == 0
  block:
    - name: Create API token {{ api_token.name }}
      ansible.builtin.command:
        pveum user token add {{ api_token.userid }} {{ api_token.name }} --privsep 0 --comment
        "Configuration by IaC." --output-format=json
      register: create_token_result
      changed_when: true

    - name: Export API token to BWS
      ansible.builtin.command:
        bws secret create {{ api_token.bws_token_name_prefix }}_{{ inventory_hostname_short | upper
        | replace('-', '_') }} {{ api_token_object.value }} {{ api_token.bws_project_id }}
      vars:
        api_token_object: '{{ create_token_result.stdout | from_json }}'
      delegate_to: localhost
      changed_when: true
