- name: Create API token
  hosts: pve
  gather_facts: true
  tasks:
    - name: Query existing tokens
      ansible.builtin.command:
        pveum user token list {{ api_token.userid }} --output-format=json
      register: query_tokens_result
      changed_when: false
      check_mode: false

    - name: Create API token {{ api_token.name }}
      ansible.builtin.command:
        pveum user token add {{ api_token.userid }} {{ api_token.name }}
          --privsep 0
          --comment "Configuration by IaC."
          --output-format=json
      when:
        query_tokens_result.stdout
          | from_json
          | selectattr('tokenid', 'equalto', api_token.name)
          | list | length == 0
      register: create_token_result
      changed_when: true
      notify: Export API token

  handlers:
    - name: Export API token to BWS
      ansible.builtin.command:
        bws secret create
          {{ api_token.bws_token_name_prefix }}_{{ ansible_hostname | upper | replace('-', '_') }}
          {{ api_token_object.value }}
          {{ api_token.bws_project_id }}
      vars:
        api_token_object: "{{ create_token_result.stdout | from_json }}"
      delegate_to: localhost
      changed_when: true
      listen: Export API token
