- name: Backup Proxmox hosts (not VMs) to PBS with the proxmox-backup-client
  hosts: pve
  gather_facts: false
  tasks:
    - name: Add cron envvar for host backup
      ansible.builtin.cron:
        env: true
        name: PBS_PASSWORD
        job: "{{ host_backup.password }}"

    - name: Add cron job for host backup
      ansible.builtin.cron:
        name: Host backup to PBS
        job:
          proxmox-backup-client backup
            --repository {{ host_backup.repository }}
            --ns {{ host_backup.namespace }}
            {{ host_backup.archives | join(' ') }}
        minute: "{{ 60 | random(seed=inventory_hostname ~ '1') }}"
        hour: "{{ 24 | random(seed=inventory_hostname ~ '1') }}"
