- name: Add backup jobs
  hosts: pve
  gather_facts: false
  tasks:
    - name: Configure backup
      ansible.builtin.include_role:
        name: pve_template
      vars:
        pve_template_src: templates/backup-jobs.cfg.j2
        pve_template_dest: /etc/pve/jobs.cfg
