- name: Install Prometheus node-exporter
  hosts: pbs,pve
  gather_facts: true
  roles:
    - role: prometheus.prometheus.node_exporter
      # renovate: datasource=github-releases packageName=prometheus/node_exporter versioning=loose
      node_exporter_version: 1.9.0
