prometheus:
  labels:
    environment: dev
  pve_exporter:
    username: pve-exporter
    password:
      "{{ lookup('password', '.credentials/{{ inventory_hostname }}/pve-exporter
      chars=ascii_letters,digits,hexdigits length=32') }}"
  remote:
    push_url: "{{ lookup('env', 'PROMETHEUS_REMOTE_PUSH_URL', default=Undefined) }}"
    username: "{{ lookup('env', 'PROMETHEUS_REMOTE_USERNAME', default=Undefined) }}"
    password: "{{ lookup('env', 'PROMETHEUS_REMOTE_PASSWORD', default=Undefined) }}"
